version: '3.8'

services:
  django_gajar:
    build: ./gajarmilega
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gajarmilega:/usr/src/app
    ports:
      - 8000:8000